// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QueryNinja.Data;

#nullable disable

namespace QueryNinja.Migrations
{
    [DbContext(typeof(QueryNinjasDbContext))]
    [Migration("20251208100814_LisaLocalTest")]
    partial class LisaLocalTest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QueryNinja.Models.ClassRoom", b =>
                {
                    b.Property<int>("ClassRoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassRoomId"));

                    b.Property<int>("RoomNumber")
                        .HasColumnType("int");

                    b.HasKey("ClassRoomId");

                    b.HasIndex("RoomNumber")
                        .IsUnique();

                    b.ToTable("ClassRooms");

                    b.HasData(
                        new
                        {
                            ClassRoomId = 1,
                            RoomNumber = 101
                        },
                        new
                        {
                            ClassRoomId = 2,
                            RoomNumber = 102
                        },
                        new
                        {
                            ClassRoomId = 3,
                            RoomNumber = 103
                        },
                        new
                        {
                            ClassRoomId = 4,
                            RoomNumber = 104
                        },
                        new
                        {
                            ClassRoomId = 5,
                            RoomNumber = 105
                        },
                        new
                        {
                            ClassRoomId = 6,
                            RoomNumber = 106
                        },
                        new
                        {
                            ClassRoomId = 7,
                            RoomNumber = 107
                        },
                        new
                        {
                            ClassRoomId = 8,
                            RoomNumber = 108
                        },
                        new
                        {
                            ClassRoomId = 9,
                            RoomNumber = 109
                        },
                        new
                        {
                            ClassRoomId = 10,
                            RoomNumber = 110
                        });
                });

            modelBuilder.Entity("QueryNinja.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FkTeacherId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CourseId");

                    b.HasIndex("CourseName")
                        .IsUnique();

                    b.HasIndex("FkTeacherId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            CourseName = "C# Programming",
                            EndDate = new DateTime(2025, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FkTeacherId = 1,
                            StartDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CourseId = 2,
                            CourseName = "Database Design",
                            EndDate = new DateTime(2025, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FkTeacherId = 2,
                            StartDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CourseId = 3,
                            CourseName = "Web Development",
                            EndDate = new DateTime(2025, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FkTeacherId = 3,
                            StartDate = new DateTime(2025, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CourseId = 4,
                            CourseName = "Software Architecture",
                            EndDate = new DateTime(2025, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FkTeacherId = 1,
                            StartDate = new DateTime(2025, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CourseId = 5,
                            CourseName = "Agile Methods",
                            EndDate = new DateTime(2025, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FkTeacherId = 4,
                            StartDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CourseId = 6,
                            CourseName = "JavaScript Basics",
                            EndDate = new DateTime(2025, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FkTeacherId = 2,
                            StartDate = new DateTime(2025, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CourseId = 7,
                            CourseName = "Cloud Computing",
                            EndDate = new DateTime(2025, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FkTeacherId = 3,
                            StartDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CourseId = 8,
                            CourseName = "DevOps",
                            EndDate = new DateTime(2025, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FkTeacherId = 4,
                            StartDate = new DateTime(2025, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CourseId = 9,
                            CourseName = "UML & Modeling",
                            EndDate = new DateTime(2025, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FkTeacherId = 1,
                            StartDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CourseId = 10,
                            CourseName = "Security Fundamentals",
                            EndDate = new DateTime(2025, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FkTeacherId = 2,
                            StartDate = new DateTime(2025, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("QueryNinja.Models.Grade", b =>
                {
                    b.Property<int>("GradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GradeId"));

                    b.Property<int>("FkCourseId")
                        .HasColumnType("int");

                    b.Property<int>("FkStudentId")
                        .HasColumnType("int");

                    b.Property<int>("FkTeacherId")
                        .HasColumnType("int");

                    b.Property<string>("GradeValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GradeId");

                    b.HasIndex("FkCourseId");

                    b.HasIndex("FkStudentId");

                    b.HasIndex("FkTeacherId");

                    b.ToTable("Grades");

                    b.HasData(
                        new
                        {
                            GradeId = 1,
                            FkCourseId = 1,
                            FkStudentId = 1,
                            FkTeacherId = 1,
                            GradeValue = "VG"
                        },
                        new
                        {
                            GradeId = 2,
                            FkCourseId = 2,
                            FkStudentId = 2,
                            FkTeacherId = 2,
                            GradeValue = "G"
                        },
                        new
                        {
                            GradeId = 3,
                            FkCourseId = 3,
                            FkStudentId = 3,
                            FkTeacherId = 3,
                            GradeValue = "IG"
                        },
                        new
                        {
                            GradeId = 4,
                            FkCourseId = 4,
                            FkStudentId = 4,
                            FkTeacherId = 1,
                            GradeValue = "VG"
                        },
                        new
                        {
                            GradeId = 9,
                            FkCourseId = 9,
                            FkStudentId = 9,
                            FkTeacherId = 1,
                            GradeValue = "G"
                        },
                        new
                        {
                            GradeId = 10,
                            FkCourseId = 10,
                            FkStudentId = 10,
                            FkTeacherId = 2,
                            GradeValue = "VG"
                        },
                        new
                        {
                            GradeId = 11,
                            FkCourseId = 1,
                            FkStudentId = 11,
                            FkTeacherId = 1,
                            GradeValue = "G"
                        },
                        new
                        {
                            GradeId = 12,
                            FkCourseId = 2,
                            FkStudentId = 12,
                            FkTeacherId = 2,
                            GradeValue = "VG"
                        },
                        new
                        {
                            GradeId = 18,
                            FkCourseId = 8,
                            FkStudentId = 18,
                            FkTeacherId = 4,
                            GradeValue = "IG"
                        },
                        new
                        {
                            GradeId = 19,
                            FkCourseId = 9,
                            FkStudentId = 19,
                            FkTeacherId = 1,
                            GradeValue = "VG"
                        },
                        new
                        {
                            GradeId = 20,
                            FkCourseId = 10,
                            FkStudentId = 20,
                            FkTeacherId = 2,
                            GradeValue = "G"
                        });
                });

            modelBuilder.Entity("QueryNinja.Models.Registration", b =>
                {
                    b.Property<int>("RegistrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegistrationId"));

                    b.Property<int>("FkCourseId")
                        .HasColumnType("int");

                    b.Property<int>("FkStudentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("RegistrationId");

                    b.HasIndex("FkCourseId");

                    b.HasIndex("FkStudentId");

                    b.ToTable("Registrations");
                });

            modelBuilder.Entity("QueryNinja.Models.Schedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleId"));

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("FkClassRoomId")
                        .HasColumnType("int");

                    b.Property<int>("FkCourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ScheduleId");

                    b.HasIndex("FkClassRoomId");

                    b.HasIndex("FkCourseId");

                    b.ToTable("Schedules");

                    b.HasData(
                        new
                        {
                            ScheduleId = 1,
                            EndTime = new DateTime(2025, 1, 15, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            FkClassRoomId = 1,
                            FkCourseId = 1,
                            StartTime = new DateTime(2025, 1, 15, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ScheduleId = 2,
                            EndTime = new DateTime(2025, 1, 15, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            FkClassRoomId = 2,
                            FkCourseId = 2,
                            StartTime = new DateTime(2025, 1, 15, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ScheduleId = 3,
                            EndTime = new DateTime(2025, 8, 20, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            FkClassRoomId = 3,
                            FkCourseId = 3,
                            StartTime = new DateTime(2025, 8, 20, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ScheduleId = 4,
                            EndTime = new DateTime(2025, 8, 20, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            FkClassRoomId = 4,
                            FkCourseId = 4,
                            StartTime = new DateTime(2025, 8, 20, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ScheduleId = 5,
                            EndTime = new DateTime(2025, 1, 15, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            FkClassRoomId = 5,
                            FkCourseId = 5,
                            StartTime = new DateTime(2025, 1, 15, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ScheduleId = 6,
                            EndTime = new DateTime(2025, 8, 20, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            FkClassRoomId = 6,
                            FkCourseId = 6,
                            StartTime = new DateTime(2025, 8, 20, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ScheduleId = 7,
                            EndTime = new DateTime(2025, 1, 15, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            FkClassRoomId = 7,
                            FkCourseId = 7,
                            StartTime = new DateTime(2025, 1, 15, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ScheduleId = 8,
                            EndTime = new DateTime(2025, 8, 20, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            FkClassRoomId = 8,
                            FkCourseId = 8,
                            StartTime = new DateTime(2025, 8, 20, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ScheduleId = 9,
                            EndTime = new DateTime(2025, 1, 15, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            FkClassRoomId = 9,
                            FkCourseId = 9,
                            StartTime = new DateTime(2025, 1, 15, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ScheduleId = 10,
                            EndTime = new DateTime(2025, 8, 20, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            FkClassRoomId = 10,
                            FkCourseId = 10,
                            StartTime = new DateTime(2025, 8, 20, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("QueryNinja.Models.StoredProcedureResult", b =>
                {
                    b.Property<string>("ResultMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("StoredProcedureResults");
                });

            modelBuilder.Entity("QueryNinja.Models.Student", b =>
                {
                    b.Property<int>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentID"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StudentID");

                    b.ToTable("Student", (string)null);

                    b.HasData(
                        new
                        {
                            StudentID = 1,
                            BirthDate = new DateTime(2000, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "anna.svensson@student.com",
                            FirstName = "Anna",
                            LastName = "Svensson"
                        },
                        new
                        {
                            StudentID = 2,
                            BirthDate = new DateTime(1999, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "erik.johansson@student.com",
                            FirstName = "Erik",
                            LastName = "Johansson"
                        },
                        new
                        {
                            StudentID = 3,
                            BirthDate = new DateTime(2001, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sara.lindgren@student.com",
                            FirstName = "Sara",
                            LastName = "Lindgren"
                        },
                        new
                        {
                            StudentID = 4,
                            BirthDate = new DateTime(1998, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "david.berg@student.com",
                            FirstName = "David",
                            LastName = "Berg"
                        },
                        new
                        {
                            StudentID = 5,
                            BirthDate = new DateTime(2000, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "emma.nystrom@student.com",
                            FirstName = "Emma",
                            LastName = "Nyström"
                        },
                        new
                        {
                            StudentID = 6,
                            BirthDate = new DateTime(1999, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "johan.persson@student.com",
                            FirstName = "Johan",
                            LastName = "Persson"
                        },
                        new
                        {
                            StudentID = 7,
                            BirthDate = new DateTime(2001, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "maja.andersson@student.com",
                            FirstName = "Maja",
                            LastName = "Andersson"
                        },
                        new
                        {
                            StudentID = 8,
                            BirthDate = new DateTime(1998, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "niklas.karlsson@student.com",
                            FirstName = "Niklas",
                            LastName = "Karlsson"
                        },
                        new
                        {
                            StudentID = 9,
                            BirthDate = new DateTime(2000, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "elin.holm@student.com",
                            FirstName = "Elin",
                            LastName = "Holm"
                        },
                        new
                        {
                            StudentID = 10,
                            BirthDate = new DateTime(1999, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "oscar.wikstrom@student.com",
                            FirstName = "Oscar",
                            LastName = "Wikström"
                        },
                        new
                        {
                            StudentID = 11,
                            BirthDate = new DateTime(2001, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "karin.aberg@student.com",
                            FirstName = "Karin",
                            LastName = "Åberg"
                        },
                        new
                        {
                            StudentID = 12,
                            BirthDate = new DateTime(1998, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mattias.forsberg@student.com",
                            FirstName = "Mattias",
                            LastName = "Forsberg"
                        },
                        new
                        {
                            StudentID = 13,
                            BirthDate = new DateTime(2000, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "linda.strom@student.com",
                            FirstName = "Linda",
                            LastName = "Ström"
                        },
                        new
                        {
                            StudentID = 14,
                            BirthDate = new DateTime(1999, 7, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "patrik.hellgren@student.com",
                            FirstName = "Patrik",
                            LastName = "Hellgren"
                        },
                        new
                        {
                            StudentID = 15,
                            BirthDate = new DateTime(2001, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sofia.blom@student.com",
                            FirstName = "Sofia",
                            LastName = "Blom"
                        },
                        new
                        {
                            StudentID = 16,
                            BirthDate = new DateTime(1998, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "andreas.lundqvist@student.com",
                            FirstName = "Andreas",
                            LastName = "Lundqvist"
                        },
                        new
                        {
                            StudentID = 17,
                            BirthDate = new DateTime(2000, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "helena.sandberg@student.com",
                            FirstName = "Helena",
                            LastName = "Sandberg"
                        },
                        new
                        {
                            StudentID = 18,
                            BirthDate = new DateTime(1999, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "marcus.viklund@student.com",
                            FirstName = "Marcus",
                            LastName = "Viklund"
                        },
                        new
                        {
                            StudentID = 19,
                            BirthDate = new DateTime(2001, 8, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ida.norberg@student.com",
                            FirstName = "Ida",
                            LastName = "Norberg"
                        },
                        new
                        {
                            StudentID = 20,
                            BirthDate = new DateTime(1998, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "per.haggstrom@student.com",
                            FirstName = "Per",
                            LastName = "Häggström"
                        });
                });

            modelBuilder.Entity("QueryNinja.Models.Teacher", b =>
                {
                    b.Property<int>("TeacherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeacherId"));

                    b.Property<string>("AreaOfExpertise")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TeacherId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Teachers", (string)null);

                    b.HasData(
                        new
                        {
                            TeacherId = 1,
                            AreaOfExpertise = "Backend Development",
                            Email = "karin.lund@school.com",
                            FirstName = "Karin",
                            LastName = "Lund"
                        },
                        new
                        {
                            TeacherId = 2,
                            AreaOfExpertise = "Databases",
                            Email = "peter.sund@school.com",
                            FirstName = "Peter",
                            LastName = "Sund"
                        },
                        new
                        {
                            TeacherId = 3,
                            AreaOfExpertise = "Frontend Development",
                            Email = "maria.ekstrom@school.com",
                            FirstName = "Maria",
                            LastName = "Ekström"
                        },
                        new
                        {
                            TeacherId = 4,
                            AreaOfExpertise = "DevOps",
                            Email = "jonas.bjork@school.com",
                            FirstName = "Jonas",
                            LastName = "Björk"
                        });
                });

            modelBuilder.Entity("QueryNinja.Models.Course", b =>
                {
                    b.HasOne("QueryNinja.Models.Teacher", "Teacher")
                        .WithMany("Courses")
                        .HasForeignKey("FkTeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("QueryNinja.Models.Grade", b =>
                {
                    b.HasOne("QueryNinja.Models.Course", "Course")
                        .WithMany("Grades")
                        .HasForeignKey("FkCourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QueryNinja.Models.Student", "Student")
                        .WithMany("Grades")
                        .HasForeignKey("FkStudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QueryNinja.Models.Teacher", "Teacher")
                        .WithMany("Grades")
                        .HasForeignKey("FkTeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("QueryNinja.Models.Registration", b =>
                {
                    b.HasOne("QueryNinja.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("FkCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QueryNinja.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("FkStudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("QueryNinja.Models.Schedule", b =>
                {
                    b.HasOne("QueryNinja.Models.ClassRoom", "ClassRoom")
                        .WithMany()
                        .HasForeignKey("FkClassRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QueryNinja.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("FkCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassRoom");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("QueryNinja.Models.Course", b =>
                {
                    b.Navigation("Grades");
                });

            modelBuilder.Entity("QueryNinja.Models.Student", b =>
                {
                    b.Navigation("Grades");
                });

            modelBuilder.Entity("QueryNinja.Models.Teacher", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Grades");
                });
#pragma warning restore 612, 618
        }
    }
}
