// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QueryNinja.Data;

#nullable disable

namespace QueryNinja.Migrations
{
    [DbContext(typeof(QueryNinjasDbContext))]
    partial class QueryNinjasDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QueryNinja.Models.ClassRoom", b =>
                {
                    b.Property<int>("ClassRoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassRoomId"));

                    b.Property<int>("RoomNumber")
                        .HasColumnType("int");

                    b.HasKey("ClassRoomId");

                    b.HasIndex("RoomNumber")
                        .IsUnique();

                    b.ToTable("ClassRooms");

                    b.HasData(
                        new
                        {
                            ClassRoomId = 1,
                            RoomNumber = 101
                        },
                        new
                        {
                            ClassRoomId = 2,
                            RoomNumber = 102
                        },
                        new
                        {
                            ClassRoomId = 3,
                            RoomNumber = 103
                        },
                        new
                        {
                            ClassRoomId = 4,
                            RoomNumber = 104
                        },
                        new
                        {
                            ClassRoomId = 5,
                            RoomNumber = 105
                        },
                        new
                        {
                            ClassRoomId = 6,
                            RoomNumber = 106
                        },
                        new
                        {
                            ClassRoomId = 7,
                            RoomNumber = 107
                        },
                        new
                        {
                            ClassRoomId = 8,
                            RoomNumber = 108
                        },
                        new
                        {
                            ClassRoomId = 9,
                            RoomNumber = 109
                        },
                        new
                        {
                            ClassRoomId = 10,
                            RoomNumber = 110
                        });
                });

            modelBuilder.Entity("QueryNinja.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FkTeacherId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CourseId");

                    b.HasIndex("CourseName")
                        .IsUnique();

                    b.HasIndex("FkTeacherId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            CourseName = "C# Programming",
                            EndDate = new DateTime(2025, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FkTeacherId = 1,
                            StartDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CourseId = 2,
                            CourseName = "Database Design",
                            EndDate = new DateTime(2025, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FkTeacherId = 2,
                            StartDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CourseId = 3,
                            CourseName = "Web Development",
                            EndDate = new DateTime(2025, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FkTeacherId = 3,
                            StartDate = new DateTime(2025, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CourseId = 4,
                            CourseName = "Software Architecture",
                            EndDate = new DateTime(2025, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FkTeacherId = 1,
                            StartDate = new DateTime(2025, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CourseId = 5,
                            CourseName = "Agile Methods",
                            EndDate = new DateTime(2025, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FkTeacherId = 4,
                            StartDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CourseId = 6,
                            CourseName = "JavaScript Basics",
                            EndDate = new DateTime(2025, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FkTeacherId = 2,
                            StartDate = new DateTime(2025, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CourseId = 7,
                            CourseName = "Cloud Computing",
                            EndDate = new DateTime(2025, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FkTeacherId = 3,
                            StartDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CourseId = 8,
                            CourseName = "DevOps",
                            EndDate = new DateTime(2025, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FkTeacherId = 4,
                            StartDate = new DateTime(2025, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CourseId = 9,
                            CourseName = "UML & Modeling",
                            EndDate = new DateTime(2025, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FkTeacherId = 1,
                            StartDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CourseId = 10,
                            CourseName = "Security Fundamentals",
                            EndDate = new DateTime(2025, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FkTeacherId = 2,
                            StartDate = new DateTime(2025, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("QueryNinja.Models.Grade", b =>
                {
                    b.Property<int>("GradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GradeId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("FkCourseId")
                        .HasColumnType("int");

                    b.Property<int>("FkStudentId")
                        .HasColumnType("int");

                    b.Property<int>("FkTeacherId")
                        .HasColumnType("int");

                    b.Property<string>("GradeValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("GradeId");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentID");

                    b.HasIndex("TeacherId");

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("QueryNinja.Models.Registration", b =>
                {
                    b.Property<int>("RegistrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegistrationId"));

                    b.Property<int>("FkCourseId")
                        .HasColumnType("int");

                    b.Property<int>("FkStudentId")
                        .HasColumnType("int");

                    b.HasKey("RegistrationId");

                    b.HasIndex("FkCourseId");

                    b.HasIndex("FkStudentId");

                    b.ToTable("Registrations");
                });

            modelBuilder.Entity("QueryNinja.Models.Schedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleId"));

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("FkClassRoomId")
                        .HasColumnType("int");

                    b.Property<int>("FkCourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ScheduleId");

                    b.HasIndex("FkClassRoomId");

                    b.HasIndex("FkCourseId");

                    b.ToTable("Schedules");

                    b.HasData(
                        new
                        {
                            ScheduleId = 1,
                            EndTime = new DateTime(2025, 1, 15, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            FkClassRoomId = 1,
                            FkCourseId = 1,
                            StartTime = new DateTime(2025, 1, 15, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ScheduleId = 2,
                            EndTime = new DateTime(2025, 1, 15, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            FkClassRoomId = 2,
                            FkCourseId = 2,
                            StartTime = new DateTime(2025, 1, 15, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ScheduleId = 3,
                            EndTime = new DateTime(2025, 8, 20, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            FkClassRoomId = 3,
                            FkCourseId = 3,
                            StartTime = new DateTime(2025, 8, 20, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ScheduleId = 4,
                            EndTime = new DateTime(2025, 8, 20, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            FkClassRoomId = 4,
                            FkCourseId = 4,
                            StartTime = new DateTime(2025, 8, 20, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ScheduleId = 5,
                            EndTime = new DateTime(2025, 1, 15, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            FkClassRoomId = 5,
                            FkCourseId = 5,
                            StartTime = new DateTime(2025, 1, 15, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ScheduleId = 6,
                            EndTime = new DateTime(2025, 8, 20, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            FkClassRoomId = 6,
                            FkCourseId = 6,
                            StartTime = new DateTime(2025, 8, 20, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ScheduleId = 7,
                            EndTime = new DateTime(2025, 1, 15, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            FkClassRoomId = 7,
                            FkCourseId = 7,
                            StartTime = new DateTime(2025, 1, 15, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ScheduleId = 8,
                            EndTime = new DateTime(2025, 8, 20, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            FkClassRoomId = 8,
                            FkCourseId = 8,
                            StartTime = new DateTime(2025, 8, 20, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ScheduleId = 9,
                            EndTime = new DateTime(2025, 1, 15, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            FkClassRoomId = 9,
                            FkCourseId = 9,
                            StartTime = new DateTime(2025, 1, 15, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ScheduleId = 10,
                            EndTime = new DateTime(2025, 8, 20, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            FkClassRoomId = 10,
                            FkCourseId = 10,
                            StartTime = new DateTime(2025, 8, 20, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("QueryNinja.Models.Student", b =>
                {
                    b.Property<int>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentID"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StudentID");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("QueryNinja.Models.Teacher", b =>
                {
                    b.Property<int>("TeacherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeacherId"));

                    b.Property<string>("AreaOfExpertise")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TeacherId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            TeacherId = 1,
                            AreaOfExpertise = "Backend Development",
                            Email = "karin.lund@school.com",
                            FirstName = "Karin",
                            LastName = "Lund"
                        },
                        new
                        {
                            TeacherId = 2,
                            AreaOfExpertise = "Databases",
                            Email = "peter.sund@school.com",
                            FirstName = "Peter",
                            LastName = "Sund"
                        },
                        new
                        {
                            TeacherId = 3,
                            AreaOfExpertise = "Frontend Development",
                            Email = "maria.ekstrom@school.com",
                            FirstName = "Maria",
                            LastName = "Ekström"
                        },
                        new
                        {
                            TeacherId = 4,
                            AreaOfExpertise = "DevOps",
                            Email = "jonas.bjork@school.com",
                            FirstName = "Jonas",
                            LastName = "Björk"
                        });
                });

            modelBuilder.Entity("QueryNinja.Models.Course", b =>
                {
                    b.HasOne("QueryNinja.Models.Teacher", "Teacher")
                        .WithMany("Courses")
                        .HasForeignKey("FkTeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("QueryNinja.Models.Grade", b =>
                {
                    b.HasOne("QueryNinja.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QueryNinja.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QueryNinja.Models.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("QueryNinja.Models.Registration", b =>
                {
                    b.HasOne("QueryNinja.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("FkCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QueryNinja.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("FkStudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("QueryNinja.Models.Schedule", b =>
                {
                    b.HasOne("QueryNinja.Models.ClassRoom", "ClassRoom")
                        .WithMany()
                        .HasForeignKey("FkClassRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QueryNinja.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("FkCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassRoom");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("QueryNinja.Models.Teacher", b =>
                {
                    b.Navigation("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
